### PR TITLE
Add assets files

### PR DESCRIPTION
**Pull request by ninabrissey**
PR Template:

Is this a fix or a feature? [] Bug fix [X] Feature [] Refactor

Describe the feature - fix - refactor: Add assets directory and necessary svgs

Additional comments: Please check to see that all asset are viable.

### CODE REVIEW

**Comment by csmucker83** [comment]
It didn't work. I only see one file.

**Review by lschnell8 — CHANGES_REQUESTED** [review]
I can only see one svg in the files. I think something may have gone wrong. Can you re-add the images?

**Review by csmucker83 — CHANGES_REQUESTED** [review]
Only see one image.

**Review by ninabrissey — COMMENTED** [review]
Please see all assets files attached. @lschnell8 @csmucker83

**Review by lschnell8 — APPROVED** [review]
Thanks for fixing that. This looks great!

**Review by csmucker83 — APPROVED** [review]
Images loaded.

**Pull request merged**
